name: Auto approve && merge PRs by dependabot

# Trigger the workflow on pull request
on: pull_request_target

jobs:
  autoapprove:
    name: Auto-Approve a PR by dependabot
    uses: unbiased-security/workflows/.github/workflows/auto-approve-and-merge.yml@main
    secrets: inherit

